### ISSUE TITLE
Pass Bus No. with Intent and Activate two buttons

### ISSUE THREAD

**Issue by The-Fuse** [The-Fuse/Driver-App#1]
These following changes are requested:
1. Pass the Bus No. with intent to the next activity to get all the details on the next page.
2.  Activate the two buttons ("TAKE A BREAK", "STOP MY DAY") on bus details activity.

**Comment by The-Fuse** [comment]
@The-Pascal would you like to work on it

**Comment by The-Pascal** [comment]
@The-Fuse yeah thanks!
You can assign this work to me.
